### PR TITLE
Update read-receipt.mdx kotlin example

### PR DESCRIPTION
**Pull request by Nicola-Ceornea**
updated kotlin "Receive a read receipt" example, as "readReceipt.timestamp" does not exist

### CODE REVIEW

**Comment by jhaaaa** [comment]
Thank you so much for taking the time to open this PR, @Nicola-Ceornea! 

Tagging an engineer for consideration - perhaps this is something we want to add to Kotlin?

More soon...

**Review by nplasterer — APPROVED** [review]

**Comment by nplasterer** [comment]
Yes we removed the timestamp from all of the readReciept codecs because it was redundant with the sent time on the message. ReadReceipts are just empty codecs now and the sent time on the message is appropriate for getting when the time of read was.

**Comment by jhaaaa** [comment]
Thank you so much @Nicola-Ceornea for your important contribution and @nplasterer for your quick and thoughtful confirmation!

Merging now. 🫡 

Nicola - you can claim this 2024 XMTP Contributor GitPOAP, if you'd like! https://www.gitpoap.io/gp/1100

**Comment by Nicola-Ceornea** [comment]
> Thank you so much @Nicola-Ceornea for your important contribution and @nplasterer for your quick and thoughtful confirmation!
> 
> Merging now. 🫡
> 
> Nicola - you can claim this 2024 XMTP Contributor GitPOAP, if you'd like! https://www.gitpoap.io/gp/1100

Im unable to claim the gitpoap. Searching my github username returns that there isn't nothing to claim. Should I move this to another communication channel? Don't won't to go off topic on here.

**Comment by jhaaaa** [comment]
> Im unable to claim the gitpoap. Searching my github username returns that there isn't nothing to claim. Should I move this to another communication channel? Don't won't to go off topic on here.

Oh gosh - so sorry about this @Nicola-Ceornea - troubleshooting now. More soon!

**Comment by Nicola-Ceornea** [comment]
> > Im unable to claim the gitpoap. Searching my github username returns that there isn't nothing to claim. Should I move this to another communication channel? Don't won't to go off topic on here.
> 
> Oh gosh - so sorry about this @Nicola-Ceornea - troubleshooting now. More soon!

Hey, I retried redeeming today. It worked :)

**Comment by jhaaaa** [comment]
Thank you so much for your patience, @Nicola-Ceornea! I misunderstood and thought every repo in the xmtp org was automatically eligible for the GitPOAP, but the repos need to be manually added. `docs-xmtp-org` is a relatively new repo and I hadn't added it. The GitPOAP team took care of this over the weekend and I'm so happy to hear that it worked for you, friend! 🫡

**Pull request merged**
