### PR TITLE
Content Types Update

### PR DESCRIPTION
**Pull request by fabriguespe**
- Updates on content types lib install code snippets.
- Added static attachment
- Replaced Lenster with Hey

### CODE REVIEW

**Comment by Monalmos** [comment]
Can

**Comment by Monalmos** [comment]
> - Updates on content types lib install code snippets.
> 
> - Added static attachment
> 
> - Replaced Lenster with Hey

**Comment by jhaaaa** [comment]
Hello @fabriguespe - Ah, so sorry this took so long to get in. 😔 I was waiting for Ry's tech review before doing my copyedit review. Do we want to go ahead and merge?

The only change I'd request is that if we don't need this file in the PR https://github.com/xmtp/docs-xmtp-org/pull/14/files#diff-33922b28c3001a542d3b810da8d6f0560fac663a391a9573dd17b9e54c8c6103 - let's remove it, please. <3

**Review by jhaaaa — APPROVED** [review]
Thank you @fabriguespe !

**Pull request merged**
