### PR TITLE
update contribute

### PR DESCRIPTION
**Pull request by Olexandr88**
update contribute

### CODE REVIEW

**Comment by Olexandr88** [comment]
It's always nice to help a project

**Comment by jhaaaa** [comment]
@Olexandr88 - I will go ahead and merge this PR now. 

In the future, once approved, you can feel free to merge a Pr you created. As the PR creator, you should have the satisfaction of clicking Merge! ❤️

**Comment by Olexandr88** [comment]
Sorry, I can't retrieve my Gitpopap, please tell me how to solve this issue

**Comment by Olexandr88** [comment]
First, it is stated that I have the right to Poаp, then I click on change and it already says that you do not have the right

**Comment by Olexandr88** [comment]
My wallet 0x237D8f9216dE4cB3b4e788bC3d091265fE5be8f2

**Comment by Olexandr88** [comment]
Thank you, it helped me

**Pull request merged**
