### PR TITLE
Docs: Update README

### PR DESCRIPTION
**Pull request by bravesasha**
Added a link to create a pull request

### CODE REVIEW

**Review by jhaaaa — APPROVED** [review]
Thank you so much, @bravesasha - LGTM!

**Comment by jhaaaa** [comment]
Wow - thank you so much for taking the time to open this PR, @bravesasha!

Once you merge your PR, you'll be eligible to claim this GitPOAP: https://www.gitpoap.io/gp/1100. If, at first, the gitPOAP doesn't show up for you, please try disconnecting and reconnecting your wallet. This usually does the trick!

Again, sending you much gratitude for your contribution!

**Comment by bravesasha** [comment]
Always happy to contribute to the development of your project

**Comment by bravesasha** [comment]
> Wow - thank you so much for taking the time to open this PR, @bravesasha!
> 
> Once you merge your PR, you'll be eligible to claim this GitPOAP: https://www.gitpoap.io/gp/1100. If, at first, the gitPOAP doesn't show up for you, please try disconnecting and reconnecting your wallet. This usually does the trick!
> 
> Again, sending you much gratitude for your contribution!

I'm sorry, but unfortunately I can't take POAP, I've already tried everything

**Pull request merged**
